apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-template-python
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-debug
    input:
      apiVersion: debug.fn.crossplane.io/v1alpha1
      kind: Input
      spec:
        depth: 2